server:
  port: 8086

spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: java.util.Map
        retry.backoff.ms: 1000
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000

elasticsearch:
  host: ${ELASTICSEARCH_HOST:http://localhost:9200}
  sessions-index: ${ELASTICSEARCH_SESSIONS_INDEX:sessions}
