ALTER TABLE mentors ADD COLUMN IF NOT EXISTS photo_url VARCHAR(512);
ALTER TABLE mentors ADD COLUMN IF NOT EXISTS work_start VARCHAR(5) DEFAULT '09:00';
ALTER TABLE mentors ADD COLUMN IF NOT EXISTS work_end VARCHAR(5) DEFAULT '21:00';
