package com.cozy.planner.service;

import java.util.Map;

public class ProfileLabels {

    private static final Map<String, Map<String, String>> LABELS = Map.of(
        "sport", Map.<String, String>ofEntries(
            Map.entry("mentor", "Тренер"),
            Map.entry("trainee", "Спортсмен"),
            Map.entry("trainee_gen", "спортсмена"),
            Map.entry("trainee_dat", "спортсмену"),
            Map.entry("trainees_acc", "спортсменів"),
            Map.entry("trainees_instr", "спортсменами"),
            Map.entry("sessions_gen", "тренувань"),
            Map.entry("session_gen", "тренування"),
            Map.entry("trainees", "Спортсмени"),
            Map.entry("trainee_search", "Пошук спортсменів..."),
            Map.entry("trainee_name_placeholder", "ПІБ спортсмена"),
            Map.entry("trainee_description_placeholder", "Примітка"),
            Map.entry("add_trainee", "Додати спортсмена"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає спортсменів"),
            Map.entry("all_trainees", "Всі спортсмени"),
            Map.entry("manage_trainees", "Спортсмени"),
            Map.entry("team", "Команда"),
            Map.entry("session", "Тренування"),
            Map.entry("sessions", "Тренування"),
            Map.entry("new_session", "Нове тренування"),
            Map.entry("create_session", "Створити тренування"),
            Map.entry("session_title_default", "Тренування"),
            Map.entry("no_sessions", "Немає тренувань на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність спортсменів"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит спортсменові:"),
            Map.entry("location", "Місце"),
            Map.entry("locations", "Місця"),
            Map.entry("no_location", "Без місця"),
            Map.entry("add_location", "Додати локацію"),
            Map.entry("location_name_placeholder", "Назва місця"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір для тренувань"),
            Map.entry("club_name_label", "Назва клубу"),
            Map.entry("club_name_placeholder", "напр. Тенісний клуб"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Катя"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Назва"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Локація"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Локація зникне з усіх тренувань."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності спортсменів."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Учень не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Тренер просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш зустрітися.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Тренеру потрібно знати, коли ти зможеш зайнятися у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Учень <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про тренування</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про тренування!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер тренер зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли учень заповнить свою доступність\n• Про майбутні тренування\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав тренер.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження тренування</b>\n\nТренер створив тренування та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Нове тренування від спортсмена</b>\n\n👤 <b>%s</b> створив нове тренування та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nТренер %s тренування:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nСпортсмен %s тренування:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Тренування підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Тренування відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Тренування підтверджено. Тренер отримає сповіщення.")
        ),
        "studying", Map.<String, String>ofEntries(
            Map.entry("mentor", "Репетитор"),
            Map.entry("trainee", "Студент"),
            Map.entry("trainee_gen", "студента"),
            Map.entry("trainee_dat", "студенту"),
            Map.entry("trainees_acc", "студентів"),
            Map.entry("trainees_instr", "студентами"),
            Map.entry("sessions_gen", "занять"),
            Map.entry("session_gen", "заняття"),
            Map.entry("trainees", "Студенти"),
            Map.entry("trainee_search", "Пошук студентів..."),
            Map.entry("trainee_name_placeholder", "ПІБ студента"),
            Map.entry("trainee_description_placeholder", "Нотатка"),
            Map.entry("add_trainee", "Додати студента"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає студентів"),
            Map.entry("all_trainees", "Всі студенти"),
            Map.entry("manage_trainees", "Студенти"),
            Map.entry("team", "Група"),
            Map.entry("session", "Заняття"),
            Map.entry("sessions", "Заняття"),
            Map.entry("new_session", "Нове заняття"),
            Map.entry("create_session", "Створити заняття"),
            Map.entry("session_title_default", "Заняття"),
            Map.entry("no_sessions", "Немає занять на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність студентів"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит студентові:"),
            Map.entry("location", "Аудиторія"),
            Map.entry("locations", "Аудиторії"),
            Map.entry("no_location", "Без аудиторії"),
            Map.entry("add_location", "Додати аудиторію"),
            Map.entry("location_name_placeholder", "Назва аудиторії"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір для занять"),
            Map.entry("club_name_label", "Назва закладу"),
            Map.entry("club_name_placeholder", "напр. Університет"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Марія"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Тема"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Аудиторія"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Аудиторія зникне з усіх занять."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності студентів."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Студент не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Репетитор просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш зустрітися.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Репетитору потрібно знати, коли ти зможеш зайнятися у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Студент <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про заняття</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про заняття!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер репетитор зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли студент заповнить свою доступність\n• Про майбутні заняття\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав репетитор.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження заняття</b>\n\nРепетитор створив заняття та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Нове заняття від студента</b>\n\n👤 <b>%s</b> створив нове заняття та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nРепетитор %s заняття:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nСтудент %s заняття:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Заняття підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Заняття відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Заняття підтверджено. Репетитор отримає сповіщення.")
        ),
        "psychology", Map.<String, String>ofEntries(
            Map.entry("mentor", "Психолог"),
            Map.entry("trainee", "Пацієнт"),
            Map.entry("trainee_gen", "пацієнта"),
            Map.entry("trainee_dat", "пацієнту"),
            Map.entry("trainees_acc", "пацієнтів"),
            Map.entry("trainees_instr", "пацієнтами"),
            Map.entry("sessions_gen", "зустрічей"),
            Map.entry("session_gen", "зустрічі"),
            Map.entry("trainees", "Пацієнти"),
            Map.entry("trainee_search", "Пошук пацієнтів..."),
            Map.entry("trainee_name_placeholder", "ПІБ пацієнта"),
            Map.entry("trainee_description_placeholder", "Нотатка"),
            Map.entry("add_trainee", "Додати пацієнта"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає пацієнтів"),
            Map.entry("all_trainees", "Всі пацієнти"),
            Map.entry("manage_trainees", "Пацієнти"),
            Map.entry("team", "Пацієнти"),
            Map.entry("session", "Зустріч"),
            Map.entry("sessions", "Зустрічі"),
            Map.entry("new_session", "Нова зустріч"),
            Map.entry("create_session", "Створити зустріч"),
            Map.entry("session_title_default", "Зустріч"),
            Map.entry("no_sessions", "Немає зустрічей на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність пацієнтів"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит пацієнтові:"),
            Map.entry("location", "Кабінет"),
            Map.entry("locations", "Кабінети"),
            Map.entry("no_location", "Без кабінету"),
            Map.entry("add_location", "Додати кабінет"),
            Map.entry("location_name_placeholder", "Назва кабінету"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір для зустрічей"),
            Map.entry("club_name_label", "Назва практики"),
            Map.entry("club_name_placeholder", "напр. Психологічний центр"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Анна"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Назва"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Кабінет"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Кабінет зникне з усіх зустрічей."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності пацієнтів."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Пацієнт не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Психолог просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш зустрітися.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Психологу потрібно знати, коли ти зможеш зустрітися у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Пацієнт <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про зустріч</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про зустріч!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер психолог зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли пацієнт заповнить свою доступність\n• Про майбутні зустрічі\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав психолог.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження зустрічі</b>\n\nПсихолог створив зустріч та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Нова зустріч від пацієнта</b>\n\n👤 <b>%s</b> створив нову зустріч та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nПсихолог %s зустріч:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nПацієнт %s зустріч:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Зустріч підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Зустріч відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Зустріч підтверджено. Психолог отримає сповіщення.")
        ),
        "other", Map.<String, String>ofEntries(
            Map.entry("mentor", "Виконавець"),
            Map.entry("trainee", "Замовник"),
            Map.entry("trainee_gen", "замовника"),
            Map.entry("trainee_dat", "замовнику"),
            Map.entry("trainees_acc", "замовників"),
            Map.entry("trainees_instr", "замовниками"),
            Map.entry("sessions_gen", "зустрічей"),
            Map.entry("session_gen", "зустрічі"),
            Map.entry("trainees", "Замовники"),
            Map.entry("trainee_search", "Пошук замовників..."),
            Map.entry("trainee_name_placeholder", "ПІБ замовника"),
            Map.entry("trainee_description_placeholder", "Нотатка"),
            Map.entry("add_trainee", "Додати замовника"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає замовників"),
            Map.entry("all_trainees", "Всі замовники"),
            Map.entry("manage_trainees", "Замовники"),
            Map.entry("team", "Команда"),
            Map.entry("session", "Зустріч"),
            Map.entry("sessions", "Зустрічі"),
            Map.entry("new_session", "Нова зустріч"),
            Map.entry("create_session", "Створити зустріч"),
            Map.entry("session_title_default", "Зустріч"),
            Map.entry("no_sessions", "Немає зустрічей на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність замовників"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит замовникові:"),
            Map.entry("location", "Місце"),
            Map.entry("locations", "Місця"),
            Map.entry("no_location", "Без місця"),
            Map.entry("add_location", "Додати локацію"),
            Map.entry("location_name_placeholder", "Назва місця"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір"),
            Map.entry("club_name_label", "Назва"),
            Map.entry("club_name_placeholder", "напр. Мій простір"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Катя"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Назва"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Локація"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Локація зникне з усіх зустрічей."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності замовників."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Замовник не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Виконавець просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш зустрітися.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Виконавцю потрібно знати, коли ти зможеш зустрітися у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Замовник <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про зустріч</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про зустріч!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер виконавець зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли замовник заповнить свою доступність\n• Про майбутні зустрічі\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав виконавець.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження зустрічі</b>\n\nВиконавець створив зустріч та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Нова зустріч від замовника</b>\n\n👤 <b>%s</b> створив нову зустріч та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nВиконавець %s зустріч:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nЗамовник %s зустріч:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Зустріч підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Зустріч відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Зустріч підтверджено. Виконавець отримає сповіщення.")
        ),
        "massage", Map.<String, String>ofEntries(
            Map.entry("mentor", "Масажист"),
            Map.entry("trainee", "Клієнт"),
            Map.entry("trainee_gen", "клієнта"),
            Map.entry("trainee_dat", "клієнту"),
            Map.entry("trainees_acc", "клієнтів"),
            Map.entry("trainees_instr", "клієнтами"),
            Map.entry("sessions_gen", "сеансів"),
            Map.entry("session_gen", "сеансу"),
            Map.entry("trainees", "Клієнти"),
            Map.entry("trainee_search", "Пошук клієнтів..."),
            Map.entry("trainee_name_placeholder", "ПІБ клієнта"),
            Map.entry("trainee_description_placeholder", "Нотатка"),
            Map.entry("add_trainee", "Додати клієнта"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає клієнтів"),
            Map.entry("all_trainees", "Всі клієнти"),
            Map.entry("manage_trainees", "Клієнти"),
            Map.entry("team", "Клієнти"),
            Map.entry("session", "Сеанс"),
            Map.entry("sessions", "Сеанси"),
            Map.entry("new_session", "Новий сеанс"),
            Map.entry("create_session", "Створити сеанс"),
            Map.entry("session_title_default", "Сеанс"),
            Map.entry("no_sessions", "Немає сеансів на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність клієнтів"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит клієнтові:"),
            Map.entry("location", "Кабінет"),
            Map.entry("locations", "Кабінети"),
            Map.entry("no_location", "Без кабінету"),
            Map.entry("add_location", "Додати кабінет"),
            Map.entry("location_name_placeholder", "Назва кабінету"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір для сеансів"),
            Map.entry("club_name_label", "Назва кабінету"),
            Map.entry("club_name_placeholder", "напр. Масажний кабінет"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Олена"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Назва"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Кабінет"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Кабінет зникне з усіх сеансів."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності клієнтів."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Клієнт не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Масажист просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш зустрітися.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Масажисту потрібно знати, коли ти зможеш прийти у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Клієнт <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про сеанс</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про сеанс!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер масажист зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли клієнт заповнить свою доступність\n• Про майбутні сеанси\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав масажист.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження сеансу</b>\n\nМасажист створив сеанс та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Новий сеанс від клієнта</b>\n\n👤 <b>%s</b> створив новий сеанс та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nМасажист %s сеанс:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nКлієнт %s сеанс:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Сеанс підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Сеанс відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Сеанс підтверджено. Масажист отримає сповіщення.")
        ),
        "manicure", Map.<String, String>ofEntries(
            Map.entry("mentor", "Майстер"),
            Map.entry("trainee", "Клієнт"),
            Map.entry("trainee_gen", "клієнта"),
            Map.entry("trainee_dat", "клієнту"),
            Map.entry("trainees_acc", "клієнтів"),
            Map.entry("trainees_instr", "клієнтами"),
            Map.entry("sessions_gen", "сеансів"),
            Map.entry("session_gen", "сеансу"),
            Map.entry("trainees", "Клієнти"),
            Map.entry("trainee_search", "Пошук клієнтів..."),
            Map.entry("trainee_name_placeholder", "ПІБ клієнта"),
            Map.entry("trainee_description_placeholder", "Нотатка"),
            Map.entry("add_trainee", "Додати клієнта"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає клієнтів"),
            Map.entry("all_trainees", "Всі клієнти"),
            Map.entry("manage_trainees", "Клієнти"),
            Map.entry("team", "Клієнти"),
            Map.entry("session", "Сеанс"),
            Map.entry("sessions", "Сеанси"),
            Map.entry("new_session", "Новий сеанс"),
            Map.entry("create_session", "Створити сеанс"),
            Map.entry("session_title_default", "Сеанс"),
            Map.entry("no_sessions", "Немає сеансів на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність клієнтів"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит клієнтові:"),
            Map.entry("location", "Салон"),
            Map.entry("locations", "Салони"),
            Map.entry("no_location", "Без салону"),
            Map.entry("add_location", "Додати салон"),
            Map.entry("location_name_placeholder", "Назва салону"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір для сеансів"),
            Map.entry("club_name_label", "Назва салону"),
            Map.entry("club_name_placeholder", "напр. Нігтьовий салон"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Аліна"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Назва"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Салон"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Салон зникне з усіх сеансів."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності клієнтів."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Клієнт не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Майстер просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш зустрітися.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Майстру потрібно знати, коли ти зможеш прийти у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Клієнт <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про сеанс</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про сеанс!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер майстер зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли клієнт заповнить свою доступність\n• Про майбутні сеанси\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав майстер.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження сеансу</b>\n\nМайстер створив сеанс та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Новий сеанс від клієнта</b>\n\n👤 <b>%s</b> створив новий сеанс та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nМайстер %s сеанс:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nКлієнт %s сеанс:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Сеанс підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Сеанс відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Сеанс підтверджено. Майстер отримає сповіщення.")
        ),
        "medicine", Map.<String, String>ofEntries(
            Map.entry("mentor", "Лікар"),
            Map.entry("trainee", "Пацієнт"),
            Map.entry("trainee_gen", "пацієнта"),
            Map.entry("trainee_dat", "пацієнту"),
            Map.entry("trainees_acc", "пацієнтів"),
            Map.entry("trainees_instr", "пацієнтами"),
            Map.entry("sessions_gen", "прийомів"),
            Map.entry("session_gen", "прийому"),
            Map.entry("trainees", "Пацієнти"),
            Map.entry("trainee_search", "Пошук пацієнтів..."),
            Map.entry("trainee_name_placeholder", "ПІБ пацієнта"),
            Map.entry("trainee_description_placeholder", "Нотатка"),
            Map.entry("add_trainee", "Додати пацієнта"),
            Map.entry("update_trainee", "Оновити"),
            Map.entry("no_trainees", "Немає пацієнтів"),
            Map.entry("all_trainees", "Всі пацієнти"),
            Map.entry("manage_trainees", "Пацієнти"),
            Map.entry("team", "Пацієнти"),
            Map.entry("session", "Прийом"),
            Map.entry("sessions", "Прийоми"),
            Map.entry("new_session", "Новий прийом"),
            Map.entry("create_session", "Створити прийом"),
            Map.entry("session_title_default", "Прийом"),
            Map.entry("no_sessions", "Немає прийомів на цей день"),
            Map.entry("availability", "Доступність"),
            Map.entry("availability_overview", "Доступність пацієнтів"),
            Map.entry("no_availability", "Немає даних про доступність"),
            Map.entry("remind_availability", "Доступність у week-end"),
            Map.entry("remind_availability_short", "Доступність у week-end"),
            Map.entry("remind_session", "⏰ Нагадувати за 1 год"),
            Map.entry("remind_session_short", "⏰ Нагадування за 1 год"),
            Map.entry("notify_availability", "Запитати Доступність"),
            Map.entry("request_availability_title", "Запросити доступність"),
            Map.entry("request_availability_body", "Надішліть запит пацієнтові:"),
            Map.entry("location", "Кабінет"),
            Map.entry("locations", "Кабінети"),
            Map.entry("no_location", "Без кабінету"),
            Map.entry("add_location", "Додати кабінет"),
            Map.entry("location_name_placeholder", "Назва кабінету"),
            Map.entry("location_description_placeholder", "Опис"),
            Map.entry("not_found", "Нічого не знайдено"),
            Map.entry("day", "День"),
            Map.entry("plan", "План"),
            Map.entry("back", "Назад"),
            Map.entry("profile", "Профіль"),
            Map.entry("info", "Інформація"),
            Map.entry("edit", "Правка"),
            Map.entry("delete", "Видалити"),
            Map.entry("cancel", "Скасувати"),
            Map.entry("save", "Зберегти"),
            Map.entry("copy", "Копіювати"),
            Map.entry("today", "Сьогодні"),
            Map.entry("color", "Колір"),
            Map.entry("setup_title", "Налаштування"),
            Map.entry("welcome_title", "Ласкаво просимо!"),
            Map.entry("welcome_subtitle", "Створіть свій простір для прийомів"),
            Map.entry("club_name_label", "Назва клініки"),
            Map.entry("club_name_placeholder", "напр. Центр здоров'я"),
            Map.entry("your_name_label", "Твоє ім'я"),
            Map.entry("your_name_placeholder", "напр. Олександр"),
            Map.entry("start_button", "Почати"),
            Map.entry("session_date", "Дата"),
            Map.entry("session_name", "Назва"),
            Map.entry("session_description", "Опис"),
            Map.entry("session_time", "Час"),
            Map.entry("session_location", "Кабінет"),
            Map.entry("delete_photo", "Видалити фото"),
            Map.entry("confirm_delete_title", "Видалити?"),
            Map.entry("confirm_delete_session", "Дію неможливо скасувати."),
            Map.entry("confirm_delete_trainee", "Дані зникнуть."),
            Map.entry("confirm_delete_location", "Кабінет зникне з усіх прийомів."),
            Map.entry("tg_connected", "TG підключено"),
            Map.entry("tg_connect", "Під'єднати TG"),
            Map.entry("tg_copy_link", "Копіювати посилання"),
            Map.entry("tg_copied", "Скопійовано!"),
            Map.entry("tg_connect_telegram", "Під'єднати Телеграм"),
            Map.entry("tg_copy_hint", "Натисніть, щоб скопіювати посилання для підключення"),
            Map.entry("tg_connected_status", "Підключено"),
            Map.entry("tg_not_configured", "Telegram не налаштовано."),
            Map.entry("tg_connect_prompt", "Підключіть Telegram, щоб отримувати сповіщення про оновлення доступності пацієнтів."),
            Map.entry("comment_optional", "Коментар (необовязково):"),
            Map.entry("comment_placeholder", "наприклад: 'на два дні', 'на наступний тиждень'"),
            Map.entry("send", "Надіслати"),
            Map.entry("sending", "Відправка..."),
            Map.entry("error_send", "Помилка відправки"),
            Map.entry("error_server", "Помилка сервера"),
            Map.entry("error_tg_not_connected", "Пацієнт не підключив Telegram."),
            Map.entry("time_passed", "Час уже минув"),
            Map.entry("reset", "Скинути"),
            Map.entry("selected_count", "вибр."),
            Map.entry("confirm_delete", "Видалити"),
            Map.entry("confirm_cancel", "Скасувати"),
            Map.entry("telegram_reminder_request", "📋 Лікар просить вказати доступність на найближчі дні.\n\n"),
            Map.entry("telegram_reminder_instruction", "<i>Будь ласка, заповни години, коли ти можеш прийти.</i>"),
            Map.entry("telegram_open_calendar", "📅 Відкрити календар"),
            Map.entry("telegram_weekend_title", "🌴 <b>Запит на доступність у вихідні</b>\n\n"),
            Map.entry("telegram_weekend_greeting", "👋 Привіт, "),
            Map.entry("telegram_weekend_body", "Будь ласка, заповни доступність на <b>суботу та неділю</b>!\n\n"),
            Map.entry("telegram_weekend_instruction", "<i>Лікарю потрібно знати, коли ти зможеш прийти у вихідні.</i>"),
            Map.entry("telegram_update_title", "✅ <b>Оновлення доступності</b>\n\n"),
            Map.entry("telegram_update_body", "Пацієнт <b>"),
            Map.entry("telegram_update_footer", "</b>щойно оновив(ла) свою доступність.\n\n"),
            Map.entry("telegram_update_hint", "<i>Перевірте календар для планування.</i>"),
            Map.entry("telegram_open_planner", "📋 Відкрити планувальник"),
            Map.entry("telegram_session_reminder_title", "⏰ <b>Нагадування про прийом</b>\n\n"),
            Map.entry("telegram_session_reminder_time", "🕐 "),
            Map.entry("telegram_session_reminder_minutes", " ...(через "),
            Map.entry("telegram_session_reminder_footer", "<i>Не забудьте про прийом!</i>"),
            Map.entry("welcome_trainee_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер лікар зможе надсилати тобі запити на заповнення доступності та нагадування.\n\nГарного дня!"),
            Map.entry("welcome_mentor_message", "🎉 Вітаємо! Твій Telegram підключено.\n\nТепер ти отримуватимеш сповіщення:\n• Коли пацієнт заповнить свою доступність\n• Про майбутні прийоми\n\nГарного дня!"),
            Map.entry("telegram_invalid_token", "❌ Невірний токен.\nЗвернись для уточнення."),
            Map.entry("telegram_connect_prompt", "👋 Привіт!\n\nЩоб підключитись, надішли мені посилання або команду /start [токен], яку дав лікар.\n\nНаприклад: /start abc123xyz"),
            Map.entry("telegram_help", "Доступні команди:\n/start - Підключити акаунт\n/help - Допомога"),
            Map.entry("telegram_session_confirmation_request", "📋 <b>Підтвердження прийому</b>\n\nЛікар створив прийом та чекає на твоє підтвердження:\n📅 %s\n🕐 %s - %s\n🏷 %s\n\nНатисни кнопку нижче, щоб підтвердити:"),
            Map.entry("telegram_new_session_from_trainee", "📋 <b>Новий прийом від пацієнта</b>\n\n👤 <b>%s</b> створив новий прийом та чекає на підтвердження:\n\n🏷 %s\n📅 %s\n🕐 %s - %s\n\nОберіть дію:"),
            Map.entry("telegram_session_confirmed_action", "підтвердив"),
            Map.entry("telegram_session_rejected_action", "відхилив"),
            Map.entry("telegram_session_decision_mentor", "%s\n\nЛікар %s прийом:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_session_decision_trainee", "%s\n\nПацієнт %s прийом:\n🏷 %s\n📅 %s\n🕐 %s - %s"),
            Map.entry("telegram_callback_confirmed", "✅ Прийом підтверджено!"),
            Map.entry("telegram_callback_rejected", "❌ Прийом відхилено."),
            Map.entry("telegram_callback_trainee_confirmed", "✅ Дякую! Прийом підтверджено. Лікар отримає сповіщення.")
        )
    );

    public static Map<String, String> getLabels(String profile) {
        return LABELS.getOrDefault(profile, LABELS.get("sport"));
    }

    public static String get(String profile, String key) {
        Map<String, String> labels = getLabels(profile);
        return labels.getOrDefault(key, key);
    }
}
