app:
  base-url: https://cozy-planner.duckdns.org

telegram:
  enabled: true
  bot-token: 8979204427:AAGd1w4zeKRahgG_6pYXJIpDsPSqvDHVQAM
  bot-username: PlanusNotificationBot
  mentor-bot-token: 8822669135:AAFwsykNyYNwzM9P_zrXfub30td-4tzpRcQ
  mentor-bot-username: PlanusMentorBot
  webhook-url: https://cozy-planner.duckdns.org/api/v1/telegram/webhook/notification
  mentor-webhook-url: https://cozy-planner.duckdns.org/api/v1/telegram/webhook/mentor
