spring:
  application:
    name: planner
  task:
    scheduling:
      pool:
        size: 4
      timezone: Europe/Kiev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/planner_db?stringtype=unspecified
    username: user
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/planner_db?stringtype=unspecified
    user: user
    password: password
    locations: classpath:db/migration
    clean-disabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:743966281289-o803jlglnt18dev0mma0c3ui78oskatb.apps.googleusercontent.com}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: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}
            scope: openid, profile, email

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  thymeleaf:
    cache: false

server:
  address: 0.0.0.0
  forward-headers-strategy: framework

app:
  flyway:
    clean-on-start: false
  base-url: ${APP_BASE_URL:https://footwork-lid-attendee.ngrok-free.dev}
  scheduler:
    weekend-reminder-cron: ${SCHEDULER_WEEKEND_REMINDER_CRON:0 0 16 * * FRI}
    session-reminder-cron: ${SCHEDULER_SESSION_REMINDER_CRON:0 */5 * * * *}

telegram:
  enabled: ${TELEGRAM_ENABLED:true}
  bot-token: ${TELEGRAM_BOT_TOKEN:8656350779:AAGYurnNw5iz5iJ71R43m0E2SVlP9ZjCjHY}
  coach-bot-token: ${TELEGRAM_BOT_TOKEN:8090987292:AAEDolG1vaazyAIUJRRxKDpgNGqxUcXtL2c}
  bot-username: ${TELEGRAM_BOT_USERNAME:CozyPlannerBot}
  coach-bot-username: ${COACH_TELEGRAM_BOT_USERNAME:CozyPlannerCoachBot}
  webhook-url: ${TELEGRAM_WEBHOOK_URL:}
  coach-webhook-url: ${COACH_TELEGRAM_WEBHOOK_URL:}
