spring:
  application:
    name: planner
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    admin:
      properties:
        retries: 10
        retry.backoff.ms: 2000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 5
        retry.backoff.ms: 1000
        delivery.timeout.ms: 120000
  devtools:
    restart:
      enabled: false
  task:
    scheduling:
      pool:
        size: 4
      timezone: Europe/Kiev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/planner_db?stringtype=unspecified
    username: user
    password: password
    pool:
      max-size: 25
      initial-size: 5
      max-create-connection-time: 5s
      max-idle-time: 10m

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/planner_db?stringtype=unspecified
    user: user
    password: password
    locations: classpath:db/migration
    clean-disabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:743966281289-o803jlglnt18dev0mma0c3ui78oskatb.apps.googleusercontent.com}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: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}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  codec:
    max-in-memory-size: 10MB

server:
  address: 0.0.0.0
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  flyway:
    clean-on-start: false
  base-url: ${APP_BASE_URL:https://footwork-lid-attendee.ngrok-free.dev}
  notification-service: ${APP_NOTIFICATION_SERVICE:kafka}
  notification-topic: ${APP_NOTIFICATION_TOPIC:notification-events}
  scheduler:
    weekend-reminder-cron: ${SCHEDULER_WEEKEND_REMINDER_CRON:0 0 16 * * FRI}
    session-reminder-cron: ${SCHEDULER_SESSION_REMINDER_CRON:0 */5 * * * *}
  search-enabled: true
  version: 6

telegram:
  enabled: ${TELEGRAM_ENABLED:true}
  bot-token: ${TELEGRAM_BOT_TOKEN:8656350779:AAGYurnNw5iz5iJ71R43m0E2SVlP9ZjCjHY}
  mentor-bot-token: ${MENTOR_TELEGRAM_BOT_TOKEN:8090987292:AAEDolG1vaazyAIUJRRxKDpgNGqxUcXtL2c}
  bot-username: ${TELEGRAM_BOT_USERNAME:CozyPlannerBot}
  mentor-bot-username: ${MENTOR_TELEGRAM_BOT_USERNAME:CozyPlannerCoachBot}
  webhook-url: ${TELEGRAM_WEBHOOK_URL:}
  mentor-webhook-url: ${MENTOR_TELEGRAM_WEBHOOK_URL:}
