spring:
  application:
    name: planner
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/planner_db?stringtype=unspecified
    username: user
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/planner_db?stringtype=unspecified
    user: user
    password: password
    locations: classpath:db/migration
    clean-disabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}                                                                                                  LSP
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  thymeleaf:
    cache: false

server:
  address: 0.0.0.0
  forward-headers-strategy: framework

app:
  flyway:
    clean-on-start: false
