server:
  port: 8085

spring:
  application:
    name: notifications
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    admin:
      properties:
        retries: 10
        retry.backoff.ms: 2000
    consumer:
      group-id: notifications-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: java.util.Map
        retry.backoff.ms: 1000
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000

telegram:
  enabled: ${TELEGRAM_ENABLED:true}
  bot-token: ${TELEGRAM_BOT_TOKEN:8656350779:AAGYurnNw5iz5iJ71R43m0E2SVlP9ZjCjHY}
  bot-username: ${TELEGRAM_BOT_USERNAME:CozyPlannerBot}
  webhook-url: ${TELEGRAM_WEBHOOK_URL:}
  mentor-bot-token: ${MENTOR_TELEGRAM_BOT_TOKEN:8090987292:AAEDolG1vaazyAIUJRRxKDpgNGqxUcXtL2c}
  mentor-bot-username: ${MENTOR_TELEGRAM_BOT_USERNAME:CozyPlannerCoachBot}
  mentor-webhook-url: ${MENTOR_TELEGRAM_WEBHOOK_URL:}

app:
  notification-sender: ${APP_NOTIFICATION_SENDER:telegram}
  notification-topic: ${APP_NOTIFICATION_TOPIC:notification-events}
  planner-base-url: ${PLANNER_BASE_URL:http://localhost:8080}
